### ISSUE TITLE
Compilation error introduced by commit 10588489

### ISSUE THREAD

**Issue by wualbert** [rbdl/rbdl#45]
I encountered a compilation error when trying to install RBDL. I ran
```
cmake -D CMAKE_BUILD_TYPE=Release -D RBDL_BUILD_PYTHON_WRAPPER=true ../
```
followed by
```
make install
```
The issue appeared on both macOS 11.6.4 and Ubuntu 20.04.3. `git blame` suggests that the change was introduced by commit `105884898b43933c5904cccab35ca7206935d2cc` and indeed reverting to the commit before that (`92e67e9f752c9533f6dcbb6892f3fcf5564bb09d`) resolved the problem.

Full error message shown below.
```
Consolidate compiler generated dependencies of target rbdl
[  7%] Building CXX object CMakeFiles/rbdl.dir/src/rbdl_mathutils.cc.o
In file included from /*/rbdl/src/rbdl_mathutils.cc:14:
In file included from /*/include/rbdl/rbdl_mathutils.h:14:
In file included from /*/rbdl/include/rbdl/rbdl_math.h:66:
/*/rbdl/include/rbdl/Quaternion.h:77:31: error:
      implicit instantiation of undefined template
      'Eigen::MatrixSquareRootReturnValue<Eigen::Matrix<double, 4, 1,
      0, 4, 1> >'
      double sin_half_theta = sqrt(1.0 - cos_half_theta * cos...
                              ^
/usr/local/include/eigen3/Eigen/src/Core/util/ForwardDeclarations.h:306:34: note:
      template is declared here
template<typename Derived> class MatrixSquareRootReturnValue;
                                 ^
In file included from /*/rbdl/src/rbdl_mathutils.cc:14:
In file included from /*/rbdl/include/rbdl/rbdl_mathutils.h:14:
In file included from /*/rbdl/include/rbdl/rbdl_math.h:66:
/*/rbdl/include/rbdl/Quaternion.h:88:24: error:
      implicit instantiation of undefined template
      'Eigen::MatrixFunctionReturnValue<Eigen::Matrix<double, 4, 1,
      0, 4, 1> >'
      double ratio_a = sin((1 - alpha) * half_theta) / sin_ha...
                       ^
/usr/local/include/eigen3/Eigen/src/Core/util/ForwardDeclarations.h:305:34: note:
      template is declared here
template<typename Derived> class MatrixFunctionReturnValue;
                                 ^
In file included from /*/rbdl/src/rbdl_mathutils.cc:14:
In file included from /*/rbdl/include/rbdl/rbdl_mathutils.h:14:
In file included from /*/rbdl/include/rbdl/rbdl_math.h:66:
/*/rbdl/include/rbdl/Quaternion.h:89:24: error:
      implicit instantiation of undefined template
      'Eigen::MatrixFunctionReturnValue<Eigen::Matrix<double, 4, 1,
      0, 4, 1> >'
      double ratio_b = sin(alpha * half_theta) / sin_half_theta;
                       ^
/usr/local/include/eigen3/Eigen/src/Core/util/ForwardDeclarations.h:305:34: note:
      template is declared here
template<typename Derived> class MatrixFunctionReturnValue;
                                 ^
In file included from /*/rbdl/src/rbdl_mathutils.cc:14:
In file included from /*/rbdl/include/rbdl/rbdl_mathutils.h:14:
In file included from /*/rbdl/include/rbdl/rbdl_math.h:66:
/*/rbdl/include/rbdl/Quaternion.h:113:19: error:
      call to non-static member function without an object argument
        float w = sqrt (1.f + tr) * 0.5;
                  ^~~~
/*/rbdl/include/rbdl/Quaternion.h:120:19: error:
      call to non-static member function without an object argument
        float x = sqrt(1.0 + mat(0,0) - mat(1,1) - mat(2,2)) * 0.5;
                  ^~~~
/*/rbdl/include/rbdl/Quaternion.h:128:19: error:
      call to non-static member function without an object argument
        float y = sqrt(1.0 + mat(1,1) - mat(0,0) - mat(2,2)) * 0.5;
                  ^~~~
/*/rbdl/include/rbdl/Quaternion.h:136:19: error:
      call to non-static member function without an object argument
        float z = sqrt(1.0 + mat(2,2) - mat(0,0) - mat(1,1)) * 0.5;
                  ^~~~
7 errors generated.
make[2]: *** [CMakeFiles/rbdl.dir/src/rbdl_mathutils.cc.o] Error 1
make[1]: *** [CMakeFiles/rbdl.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by quentin-leboutet** [comment]
Hi, I propose a simple fix in #46
