### ISSUE TITLE
Error when building with RBDL_BUILD_ADDON_URDFREADER ON

### ISSUE THREAD

**Issue by lucanunz** [rbdl/rbdl#94]
I can build the repo following the instruction if RBDL_BUILD_ADDON_URDFREADER is OFF, but when I turn it ON it gives me the following errors. I cloned the repo recursively, so I do not think that's the issue. I am working on Ubuntu 20.04 and python 3. Can anyone help? Thank you.
```c++

/home/luca/rbdl/addons/urdfreader/urdfreader.cc: In function ‘RigidBodyDynamics::Body RigidBodyDynamics::Addons::get_rbdl_body(const LinkPtr&, bool)’:
/home/luca/rbdl/addons/urdfreader/urdfreader.cc:128:14: error: ‘urdf_child’ was not declared in this scope
  128 |     auto I = urdf_child->inertial;
      |              ^~~~~~~~~~
/home/luca/rbdl/addons/urdfreader/urdfreader.cc: In function ‘void RigidBodyDynamics::Addons::construct_model(RigidBodyDynamics::Model*, ModelPtr, const string&, bool, bool)’:
/home/luca/rbdl/addons/urdfreader/urdfreader.cc:307:39: error: invalid initialization of reference of type ‘const LinkPtr&’ {aka ‘const std::shared_ptr<urdf::Link>&’} from expression of type ‘ConstLinkPtr’ {aka ‘const std::shared_ptr<const urdf::Link>’}
  307 |   Body root_link_body = get_rbdl_body(root, true);
      |                                       ^~~~
/home/luca/rbdl/addons/urdfreader/urdfreader.cc:115:35: note: in passing argument 1 of ‘RigidBodyDynamics::Body RigidBodyDynamics::Addons::get_rbdl_body(const LinkPtr&, bool)’
  115 | Body get_rbdl_body(const LinkPtr &urdf_link, bool is_root_link)
      |                    ~~~~~~~~~~~~~~~^~~~~~~~~
/home/luca/rbdl/addons/urdfreader/urdfreader.cc: In function ‘void RigidBodyDynamics::Addons::construct_partial_model(RigidBodyDynamics::Model*, ModelPtr, const string&, const std::vector<std::__cxx11::basic_string<char> >&, bool, bool)’:
/home/luca/rbdl/addons/urdfreader/urdfreader.cc:409:41: error: invalid initialization of reference of type ‘const LinkPtr&’ {aka ‘const std::shared_ptr<urdf::Link>&’} from expression of type ‘ConstLinkPtr’ {aka ‘const std::shared_ptr<const urdf::Link>’}
  409 |     Body root_link_body = get_rbdl_body(root, true);
      |                                         ^~~~
/home/luca/rbdl/addons/urdfreader/urdfreader.cc:115:35: note: in passing argument 1 of ‘RigidBodyDynamics::Body RigidBodyDynamics::Addons::get_rbdl_body(const LinkPtr&, bool)’
  115 | Body get_rbdl_body(const LinkPtr &urdf_link, bool is_root_link)
```

**Comment by lucanunz** [comment]
Found that this is a duplicate from #85.
